name: Build Desktop App (Tauri) — Windows only

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build

      - name: Install tauri-cli
        run: cargo install tauri-cli || true

- name: Install WiX Toolset (for MSI)
  if: runner.os == 'Windows'
  run: choco install wixtoolset --no-progress -y

      - name: Build (Tauri, verbose)
        working-directory: src-tauri
        env:
          RUST_BACKTRACE: 1
        run: cargo tauri build --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lora-gui-windows
          path: src-tauri/target/release/bundle/**
